version: 0.0.1-BETA

# Configure the item used to freeze/unfreeze the block.
item:
  material: HONEYCOMB
  name: "&bBlock Freezer"
  lore:
      - "&7Freeze the block."
      - "&7Right click to freeze."
      - "&7Left click to unfreeze."

# In this list, you can add all the types of block that continue to grow even after being frozen.
# Because of the Bukkit API, it is not possible to recover the source.
#
# Adding them to this list will therefore tell the plugin that it needs to
# check the block below the one that has just appeared to cancel the growth.
vertical_blocks:
  - "SUGAR_CANE"
  - "CACTUS"
  - "BAMBOO"

# Disable the use of the freeze item in the following worlds.
disabled_worlds:
  - "world_nether"
  - "world_the_end"

# If enabled, the player will not be able to use the block freezer in a worldguard region.
use_worldguard: false
